# Generated by Django 5.2.4 on 2025-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogImg',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/built-in-method-title-of-str-object-at-0x106a124f0-279fe9d1.blog_images'),
        ),
    ]
