# Generated by Django 5.2.4 on 2025-07-24 08:52

import blog.utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogImg',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.file_uploads.unique_image_path),
        ),
    ]
