# Generated by Django 5.2.4 on 2025-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_alter_blog_blog_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/built-in-method-title-of-str-object-at-0x1070bcab0-4f40809e.blog_images'),
        ),
    ]
