# Generated by Django 5.2.4 on 2025-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_slug_alter_blog_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs\\built-in-method-title-of-str-object-at-0x000001c013a13090-c2994222.blog_images'),
        ),
    ]
