# Generated by Django 5.2.4 on 2025-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/built-in-method-title-of-str-object-at-0x1056c0d80-5ad32df5.blog_images'),
        ),
    ]
